### ISSUE TITLE
Add ETSI MANO

### ISSUE THREAD

**Issue by jgroom33** [BernardTsai/vnf-designer#6]
Add an export option for ETSI/MANO DSL:

* VNFd
* NSd

**Comment by BernardTsai** [comment]
Great!

**Comment by jgroom33** [comment]
they are started here (vnfd):
https://github.com/jgroom33/blueplanet-vnf-designer/blob/e13c35194b326e10395c905433d55a5030443761/src/templates.js#L135

but, they need to be converted to yaml and completed.
