### ISSUE TITLE
move templates to individual files

### ISSUE THREAD

**Issue by jgroom33** [BernardTsai/vnf-designer#8]
Move each item in [this array](https://github.com/BernardTsai/vnf-designer/blob/master/src/vnf_modules/templates.js) to individual files

i.e. Canonical.j2

**Comment by BernardTsai** [comment]
With which technology would you dynamically load these *.j2 files into an offline version of the VNF designer?

**Comment by jgroom33** [comment]
Not sure yet.  I'm assuming the vue build step would handle the compiling.

**Comment by BernardTsai** [comment]
OK - I will think of an approach here.

**Comment by jgroom33** [comment]
maybe this: https://www.npmjs.com/package/raw-loader

**Comment by BernardTsai** [comment]
The templates have been split up into distinct jinja2 files located in the templates subdirectory and are assembled via raw-loader in the templates.js file.
