### ISSUE TITLE
use github-pages branch

### ISSUE THREAD

**Issue by jgroom33** [BernardTsai/vnf-designer#9]
The initial implementation of using the /docs directory was a bit of a hack.

**Comment by jgroom33** [comment]
Looks like there is a publish github action that supports this:
https://github.com/peaceiris/actions-gh-pages

**Comment by BernardTsai** [comment]
I am no expert regarding github actions - would you be able to make the required adjustments?

**Comment by jgroom33** [comment]
i think it might be working

**Comment by jgroom33** [comment]
i added this files: https://github.com/BernardTsai/vnf-designer/blob/master/.github/workflows/pages.yml

and it does this: https://github.com/BernardTsai/vnf-designer/runs/615534831?check_suite_focus=true

**Comment by jgroom33** [comment]
I think this is complete.  Did you update the settings so it points to the gh-pages branch?   i assume so, because the docs directory doesn't exist anymore and there are no failures.

**Comment by BernardTsai** [comment]
I did not update the settings to my knowledge at least.
